ProyectoEnvios/Controllers/EnvioController.cs
using ProyectoEnvios.Datos;
using ProyectoEnvios.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoEnvios.Controllers
{
    public class EnvioController : Controller
    {

        EnvioAD eAD = new EnvioAD();
        // GET: Envio
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult registrarEnvio()
        {

            return View();
        }

        [HttpPost]
        public ActionResult registrarEnvio(EnvioCS envioCS)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                string msg = eAD.registrarEnvio(envioCS);
                if (!msg.Contains("error"))
                {
                    TempData["Exito"] = "Envio registrado, N° de guia:" + msg;
                    return RedirectToAction("ConsultaGuia", new { id = msg });
                    //ViewData["Exito"] = msg;
                    //return View();
                }
                else
                {

                    if (msg.Contains("Destinatario"))
                    {
                        ViewData["Error"] = "No se encuentra registrado el destinatario";
                        return View();
                    }
                    else
                    {
                        ViewData["Error"] = "No se encuentra registrado el remitente";
                        return View();
                    }

                }
            }
            catch (Exception ex)
            {
                string msg = "Error al crear al cliente " + ex;
                ModelState.AddModelError("Error al crear el cliente, ", ex);
                ViewData["Error"] = msg;
                return View();
            }
        }

        public ActionResult ConsultaGuia(int id)
        {
            try
            {
                EnvioCS e = new EnvioCS();
                e = eAD.consultarGuia(id);
                if (e.idEnvio != 0)
                {
                    return View(e);
                }
                else
                {
                    ViewData["Error"] = "El numero de guia ingresado no existe";
                    return View();
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error al logear, ", ex.Message);
                return View();
            }
        }

        [HttpPost]
        public ActionResult ConsultaGuia(EnvioCS eS)
        {
            int id = eS.idEnvio;
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                string msg = eAD.actualizarEstado(eS);
                if (!msg.Contains("error"))
                {
                    TempData["Exito"] = msg;
                    return RedirectToAction("ConsultaGuia", new { id = eS.idEnvio });
                }
                else
                {
                    TempData["Error"] = msg;
                    return RedirectToAction("ConsultaGuia", new { id = eS.idEnvio });
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error al actualizar estado, ", ex.Message);
                return RedirectToAction("ConsultaGuia", new { id = eS.idEnvio });
            }
        }

        public ActionResult consultarEnvios()
        {
            try
            {
                return View(eAD.listarEnvios());
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error al consultar envios, ", ex.Message);
                return View();
            }

        }




        public ActionResult _ListarCiudades(int id)
        {
            ViewData["id"] = id.ToString();
            return PartialView(eAD.listaCiudades());
        }

        public ActionResult _ListarEstados()
        {
            return PartialView(eAD.listaEstado());
        }

        public ActionResult _ListarProductos()
        {
            return PartialView(eAD.listaProductos());
        }

        public ActionResult Logout()
        {
            Session.Abandon();
            return RedirectToAction("Login", "Home");
        }


    }
}

ProyectoEnvios/Controllers/UsuarioController.cs
using ProyectoEnvios.Datos;
using ProyectoEnvios.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoEnvios.Controllers
{
    public class UsuarioController : Controller
    {

        ClienteAD cAD = new ClienteAD();

        // GET: Usuario
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(ClienteCS cS)
        {
            try
            {
                ClienteCS c = new ClienteCS();
                c = cAD.login(cS.Usuario, cS.Pass);
                if (c.NombreUsuario != null)
                {
                    Session["userID"] = c.NombreUsuario + " " + c.ApellidoUsuario;
                    return RedirectToAction("consultarClientes");
                }
                else
                {
                    ViewData["Error"] = "Usuario o contraseña erroneo, por favor valide";
                    return View();
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error al logear, ", ex.Message);
                return View();
            }
        }


        public ActionResult Logout()
        {
            Session.Abandon();
            return RedirectToAction("Login");
        }

        public ActionResult consultarClientes()
        {
            try
            {
                if (TempData["Exito"] != null)
                {
                    ViewData["Exito"] = TempData["Exito"];
                    return View(cAD.consultarClientes());
                }
                else
                {
                    return View(cAD.consultarClientes());
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error al consultar clientes, ", ex.Message);
                return View();
            }


        }

        public ActionResult agregarCliente()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult agregarCliente(ClienteCS cS)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                string msg = cAD.agregarCliente(cS);
                if (!msg.Contains("error"))
                {
                    TempData["Exito"] = msg;
                    return RedirectToAction("consultarClientes");
                }
                else
                {
                    ViewData["Error"] = msg;
                    return View();
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error al crear el cliente, ", ex.Message);
                return View();
            }
        }

        public ActionResult ListarDocumentos(int id)
        {
            ViewData["id"] = id.ToString();
            return PartialView(cAD.listaDocumentos());

        }


        public ActionResult editarCliente(int id)
        {
            try
            {
                ClienteCS cS = cAD.consultarClienteID(id);
                return View(cS);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error al traer informacion del cliente, ", ex.Message);
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult editarCliente(ClienteCS cS)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                string msg = cAD.editarCliente(cS);
                if (!msg.Contains("error"))
                {
                    TempData["Exito"] = msg;
                    return RedirectToAction("consultarClientes");
                }
                else
                {
                    ViewData["Error"] = msg;
                    return View(cS);
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error al modificar cliente, ", ex.Message);
                return View(cS);
            }
        }

        public ActionResult borrarCliente(int id)
        {
            try
            {
                string msg = cAD.borrarCliente(id);
                if (!msg.Contains("error"))
                {
                    TempData["Exito"] = msg;
                }
                else
                {
                    TempData["Error"] = msg;
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error al modificar cliente, ", ex.Message);
            }
            return RedirectToAction("consultarClientes");
        }
    }
}

ProyectoEnvios/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Proyecto Envios</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar">awdawd</span>
                    <span class="icon-bar">ergerg</span>
                    <span class="icon-bar">qweqweqw</span>
                </button>
                @if (Session["userID"] == null)
                {
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</li>
                    </ul>
                }
                else
                {
                    string[] user = Session["userID"].ToString().Split(',');
                    switch (user[1])
                    {
                        case "Cliente":
                            <div class="navbar-collapse collapse">
                                <ul class="nav navbar-nav">
                                    <li>@Html.ActionLink("Inicio", "Index", "Usuario", new { area = "" }, new { @class = "navbar-brand" })</li>
                                </ul>
                                <form class="navbar-form navbar-left" action="@Url.Action("ConsultaGuia","Envio")">
                                    <div class="input-group">
                                        <input type="text" id="id" name="id" class="form-control" placeholder="N° Guia">
                                        <div class="input-group-btn">
                                            <button class="btn btn-default" type="submit">
                                                <i class="glyphicon glyphicon-search"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            break;
                        case "Trabajador":
                            <div class="navbar-collapse collapse">
                                <ul class="nav navbar-nav">
                                    <li>@Html.ActionLink("Inicio", "Index", "Trabajador", new { area = "" }, new { @class = "navbar-brand" })</li>
                                    <li>@Html.ActionLink("Registrar envio", "registrarEnvio", "Envio")</li>
                                    <li>@Html.ActionLink("Consultar envios", "consultarEnvios", "Envio")</li>
                                    <li class="dropdown">
                                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Clientes <span class="caret"></span></a>
                                        <ul class="dropdown-menu">
                                            <li>@Html.ActionLink("Registrar clientes", "agregarCliente", "Trabajador")</li>
                                            <li>@Html.ActionLink("Consultar clientes", "consultarClientes", "Trabajador")</li>
                                        </ul>
                                    </li>
                                </ul>
                                <form class="navbar-form navbar-left" action="@Url.Action("ConsultaGuia","Envio")">
                                    <div class="input-group">
                                        <input type="text" id="id" name="id" class="form-control" placeholder="N° Guia">
                                        <div class="input-group-btn">
                                            <button class="btn btn-default" type="submit">
                                                <i class="glyphicon glyphicon-search"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            break;
                        case "Mensajero":
                            <div class="navbar-collapse collapse">
                                <ul class="nav navbar-nav">
                                    <li>@Html.ActionLink("Inicio", "Index", "Mensajero", new { id = user[2] }, new { @class = "navbar-brand" })</li>
                                    <li>@Html.ActionLink("Consultar envios", "consultarEnvios", "Envio")</li>
                                </ul>
                                <form class="navbar-form navbar-left" action="@Url.Action("ConsultaGuia","Envio")">
                                    <div class="input-group">
                                        <input type="text" id="id" name="id" class="form-control" placeholder="N° Guia">
                                        <div class="input-group-btn">
                                            <button class="btn btn-default" type="submit">
                                                <i class="glyphicon glyphicon-search"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            break;
                        default:
                            <ul class="nav navbar-nav">
                                <li>@Html.ActionLink("Login", "Login", "Home")</li>
                            </ul>
                            break;
                    }
                }
            </div>
            <div class="nav navbar-nav navbar-right">
                @if (Session["userID"] == null)
                {
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Login", "Login", "Home")</li>
                    </ul>
                }
                else
                {
                    string[] user = Session["userID"].ToString().Split(',');

                    <span class="nav navbar-text">Bienvenido, @user[0]</span>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#" data-toggle="modal" data-target="#logoutModal">Logout</a></li>
                    </ul>
                }

            </div>

        </div>
    </div>
    <div class="container body-content">
        <!-- Logout Modal-->
        <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title text-danger">
                            Seguro desea cerrar sesion?
                            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                        </h5>
                    </div>
                    <div class="modal-body">Presione "Logout" si desea cerrar su sesion actual</div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                        @Html.ActionLink("Logout", "Logout", "Usuario", new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>
        </div>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Cristian H. Barreto</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>