ProyectoEnvios/Controllers/EnvioController.cs
using ProyectoEnvios.Datos;
using ProyectoEnvios.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoEnvios.Controllers
{
    public class EnvioController : Controller
    {

        EnvioAD eAD = new EnvioAD();
        // GET: Envio
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult registrarEnvio()
        {

            return View();
        }

        [HttpPost]
        public ActionResult registrarEnvio(EnvioCS envioCS)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                string msg = eAD.registrarEnvio(envioCS);
                if (!msg.Contains("error"))
                {
                    TempData["Exito"] = "Envio registrado, N° de guia:" + msg;
                    return RedirectToAction("ConsultaGuia", new { id = msg });
                    //ViewData["Exito"] = msg;
                    //return View();
                }
                else
                {

                    if (msg.Contains("Destinatario"))
                    {
                        ViewData["Error"] = "No se encuentra registrado el destinatario";
                        return View();
                    }
                    else
                    {
                        ViewData["Error"] = "No se encuentra registrado el remitente";
                        return View();
                    }

                }
            }
            catch (Exception ex)
            {
                string msg = "Error al crear al cliente " + ex;
                ModelState.AddModelError("Error al crear el cliente, ", ex);
                ViewData["Error"] = msg;
                return View();
            }
        }

        public ActionResult ConsultaGuia(int id)
        {
            try
            {
                EnvioCS e = new EnvioCS();
                e = eAD.consultarGuia(id);
                if (e.idEnvio != 0)
                {
                    return View(e);
                }
                else
                {
                    ViewData["Error"] = "El numero de guia ingresado no existe";
                    return View();
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error al logear, ", ex.Message);
                return View();
            }
        }

        [HttpPost]
        public ActionResult ConsultaGuia(EnvioCS eS)
        {
            int id = eS.idEnvio;
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                string msg = eAD.actualizarEstado(eS);
                if (!msg.Contains("error"))
                {
                    TempData["Exito"] = msg;
                    return RedirectToAction("ConsultaGuia", new { id = eS.idEnvio });
                }
                else
                {
                    TempData["Error"] = msg;
                    return RedirectToAction("ConsultaGuia", new { id = eS.idEnvio });
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error al actualizar estado, ", ex.Message);
                return RedirectToAction("ConsultaGuia", new { id = eS.idEnvio });
            }
        }

        public ActionResult consultarEnvios()
        {
            try
            {
                return View(eAD.listarEnvios());
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error al consultar envios, ", ex.Message);
                return View();
            }

        }




        public ActionResult _ListarCiudades(int id)
        {
            ViewData["id"] = id.ToString();
            return PartialView(eAD.listaCiudades());
        }

        public ActionResult _ListarEstados()
        {
            return PartialView(eAD.listaEstado());
        }

        public ActionResult _ListarProductos()
        {
            return PartialView(eAD.listaProductos());
        }

        public ActionResult Logout()
        {
            Session.Abandon();
            return RedirectToAction("Login", "Home");
        }


    }
}

ProyectoEnvios/Controllers/TrabajadorController.cs
using ProyectoEnvios.Datos;
using ProyectoEnvios.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoEnvios.Controllers
{
    public class TrabajadorController : Controller
    {
        // GET: Trabajador
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Logout()
        {
            Session.Abandon();
            return RedirectToAction("Login", "Home");
        }

        ClienteAD cAD = new ClienteAD();

        public ActionResult consultarClientes()
        {
            try
            {
                if (TempData["Exito"] != null)
                {
                    ViewData["Exito"] = TempData["Exito"];
                    return View(cAD.consultarClientes());
                }
                else
                {
                    return View(cAD.consultarClientes());
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error al consultar clientes, ", ex.Message);
                return View();
            }


        }

        public ActionResult agregarCliente()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult agregarCliente(ClienteCS cS)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                string msg = cAD.agregarCliente(cS);
                if (!msg.Contains("error"))
                {
                    TempData["Exito"] = msg;
                    return RedirectToAction("consultarClientes");
                }
                else
                {
                    ViewData["Error"] = msg;
                    return View();
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error al crear el cliente, ", ex.Message);
                return View();
            }
        }

        public ActionResult ListarDocumentos(int id)
        {
            ViewData["id"] = id.ToString();
            return PartialView(cAD.listaDocumentos());

        }

        public ActionResult ListarRoles(int id)
        {
            ViewData["id"] = id.ToString();
            return PartialView(cAD.listaRoles());

        }


        public ActionResult editarCliente(int id)
        {
            try
            {
                ClienteCS cS = cAD.consultarClienteID(id);
                return View(cS);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error al traer informacion del cliente, ", ex.Message);
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult editarCliente(ClienteCS cS)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                string msg = cAD.editarCliente(cS);
                if (!msg.Contains("error"))
                {
                    TempData["Exito"] = msg;
                    return RedirectToAction("consultarClientes");
                }
                else
                {
                    ViewData["Error"] = msg;
                    return View(cS);
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error al modificar cliente, ", ex.Message);
                return View(cS);
            }
        }

        public ActionResult borrarCliente(int id)
        {
            try
            {
                string msg = cAD.borrarCliente(id);
                if (!msg.Contains("error"))
                {
                    TempData["Exito"] = msg;
                }
                else
                {
                    TempData["Error"] = msg;
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error al modificar cliente, ", ex.Message);
            }
            return RedirectToAction("consultarClientes");
        }
    }
}

ProyectoEnvios/Views/Envio/ConsultaGuia.cshtml
@model ProyectoEnvios.Models.EnvioCS

@{
    ViewBag.Title = "ConsultaGuia";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Consulta de la Guia #@Html.DisplayFor(model => model.idEnvio)</h2>

@{
    var dateRe = "";
    var hourRe = "";
    var dateEn = "";
    var hourEn = "";
}

<div class="container">

    @if (TempData["Exito"] != null)
    {
        <div class="alert alert-success" role="alert">
            <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
            <span class="sr-only">Exito:</span>
            @TempData["Exito"].ToString()
        </div>
    }

    @if (ViewData["Exito"] != null)
    {
        <div class="alert alert-success" role="alert">
            <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
            <span class="sr-only">Exito:</span>
            @ViewData["Exito"].ToString()
        </div>
    }

    @if (ViewData["Error"] != null)
    {
        if (Session["userID"] != null)
        {
            <div class="alert alert-danger" role="alert">
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                <span class="sr-only">Error:</span>
                @ViewData["Error"].ToString()
            </div>
        }
        else
        {<div class="alert alert-danger" role="alert">
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                <span class="sr-only">Error:</span>
                @ViewData["Error"].ToString(), @Html.ActionLink("Click para volver atras", "Index", "Home", new { area = "" }, new { @class = "text-danger" })
            </div>
        }
    }
    else
    {
        switch (Model.estado)
        {
            case "Entregado":
                <h4 class="text-success">Estado: @Html.DisplayFor(model => model.estado)</h4>
                break;
            case "Rechazado":
                <h4 class="text-danger">Estado: @Html.DisplayFor(model => model.estado)</h4>
                break;
            default:
                <h4 class="text-primary">Estado: @Html.DisplayFor(model => model.estado)</h4>
                break;
        }
        dateRe = Model.fechaRecepcion.ToShortDateString();
        hourRe = Model.fechaRecepcion.ToShortTimeString();
        dateEn = Model.fechaEntrega.ToShortDateString();
        hourEn = Model.fechaEntrega.ToShortTimeString();
    }



    @if (Session["userID"] != null)
    {
        <hr />
        string[] user = Session["userID"].ToString().Split(',');
        if (user[1].Equals("Mensajero"))
        {
            using (Html.BeginForm())
            {
                <input name="idEnvio" id="idEnvio" hidden="hidden" value="@Model.idEnvio" />
                <div class="row">
                    <div class="col-md-4 col-md-offset-1">
                        <div class="form-group">
                            @Html.LabelFor(model => model.estado, htmlAttributes: new { @class = "control-label col-md-5" })
                            <br /><br />
                            <div class="col-md-10">
                                @Html.Action("_ListarEstados")
                                @Html.ValidationMessageFor(model => model.idEstado, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="form-group">
                            <br /><br />
                            <div class="col-md-1">
                                <input type="submit" value="Cambiar Estado" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                </div>
            }
        }
    }



    <hr />

    <div class="container-fluid col-md-8 col-md-offset-2">
        <div class="row">
            <h3 style="background-color:lightgray; padding:10px;">REMITENTE/ORIGEN</h3>
            <hr />
            <div class="col-md-5 col-md-offset-1">
                <p>Ciudad de Origen</p>
                <p>@Html.DisplayFor(model => model.origen)</p>
            </div>
            <div class="col-md-5 col-md-offset-1">
                <p>Ciudad de Destino</p>
                <p>@Html.DisplayFor(model => model.destino)</p>
            </div>
        </div>
        <div class="row">
            <hr />
            <div class="col-md-5 col-md-offset-1">
                <p>Fecha de Repecion</p>
                <p>@Html.DisplayFor(model => dateRe)</p>
            </div>
            <div class="col-md-5 col-md-offset-1">
                <p>Hora de Recepcion</p>
                <p>@Html.DisplayFor(model => hourRe)</p>
            </div>
        </div>
        <div class="row">
            <hr />
            <div class="col-md-5 col-md-offset-1">
                <p>Nombre de Remitente</p>
                <p>@Html.DisplayFor(model => model.nombreRemitente)</p>
            </div>
            <div class="col-md-5 col-md-offset-1">
                <p>Direccion</p>
                <p>@Html.DisplayFor(model => model.direccionOrigen)</p>
            </div>
        </div>
        <div class="row">
            <hr />
            <div class="col-md-5 col-md-offset-1">
                <p>Tipo de Producto</p>
                <p>@Html.DisplayFor(model => model.tipoProducto)</p>
            </div>
            <div class="col-md-5 col-md-offset-1">
                <p>Peso total (Kg)</p>
                <p>@Html.DisplayFor(model => model.peso)</p>
            </div>
        </div>


        <div class="row">
            <h3 style="background-color:lightgray; padding:10px;">DESTINATARIO/DESTINO</h3>
            <hr />
            <div class="col-md-5 col-md-offset-1">
                <p>Ciudad de Origen</p>
                <p>@Html.DisplayFor(model => model.origen)</p>
            </div>
            <div class="col-md-5 col-md-offset-1">
                <p>Ciudad de Destino</p>
                <p>@Html.DisplayFor(model => model.destino)</p>
            </div>
        </div>
        <div class="row">
            <hr />
            <div class="col-md-5 col-md-offset-1">
                <p>Fecha de Entrega</p>
                <p>@Html.DisplayFor(model => dateEn)</p>
            </div>
            <div class="col-md-5 col-md-offset-1">
                <p>Hora de Entrega</p>
                <p>@Html.DisplayFor(model => hourEn)</p>
            </div>
        </div>
        <div class="row">
            <hr />
            <div class="col-md-5 col-md-offset-1">
                <p>Nombre de Destinatario</p>
                <p>@Html.DisplayFor(model => model.nombreDestinatario)</p>
            </div>
            <div class="col-md-5 col-md-offset-1">
                <p>Direccion</p>
                <p>@Html.DisplayFor(model => model.direccionDestino)</p>
            </div>
        </div>
    </div>

</div>
@if (Session["userID"] == null)
{
    <div class="row">
        <p>
            @Html.ActionLink("Volver Atras", "Index", "Home")
        </p>
    </div>
}

ProyectoEnvios/Views/Envio/_ListarCiudades.cshtml
@model IEnumerable<ProyectoEnvios.Models.Ciudades>


@if (ViewData["id"].ToString().Equals("1"))
{
    <select class="form-control" id="idOrigen" name="idOrigen">
        @foreach (var item in Model)
        {
            <option value="@item.idCiudades">@item.nombreCiudades</option>
        }
    </select>
}
else
{
    <select class="form-control" id="idDestino" name="idDestino">
        @foreach (var item in Model)
        {
            <option value="@item.idCiudades">@item.nombreCiudades</option>
        }
    </select>
}

ProyectoEnvios/Views/Envio/_ListarEstados.cshtml
@model IEnumerable<ProyectoEnvios.Models.Estado>

<select class="form-control" id="idEstado" name="idEstado">
    @foreach (var item in Model)
    {
        <option value="@item.idEstado">@item.estado</option>
    }
</select>

ProyectoEnvios/Views/Envio/_ListarProductos.cshtml
@model IEnumerable<ProyectoEnvios.Models.TipoProducto>

<select class="form-control" id="idTipoProducto" name="idTipoProducto">
    @foreach (var item in Model)
    {
        <option value="@item.idTipoProducto">@item.nombreTipoProducto</option>
    }
</select>

ProyectoEnvios/Views/Envio/_consultarCliente.cshtml
@model ProyectoEnvios.Models.ClienteCS

<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
            @Html.DisplayNameFor(model => model.IdentificacionUsuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdentificacionUsuario)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.NombreUsuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreUsuario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApellidoUsuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApellidoUsuario)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.Direcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telefono)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.EdadUsuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EdadUsuario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoDocumento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoDocumento)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.Usuario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Usuario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NombreDocumento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreDocumento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.idRol)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.idRol)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rol)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rol)
        </dd>*@

        @Html.ActionLink("agregarCliente","Trabajador")

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ProyectoEnvios/Views/Envio/consultarEnvios.cshtml
@model IEnumerable<ProyectoEnvios.Models.EnvioCS>

@{
    ViewBag.Title = "Consultar Envios";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Listado de envios</h2>
<div class="container">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.idEnvio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nombreDestinatario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.destino)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.direccionDestino)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fechaRecepcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fechaEntrega)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.estado)
            </th>
        </tr>

        @foreach (var item in Model)
        {
            var fechaEntrega = item.fechaEntrega.ToShortDateString();
            var fechaRecepcion = item.fechaRecepcion.ToShortDateString();
            var estado = item.estado;
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.idEnvio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nombreDestinatario)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.direccionDestino)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.destino)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => fechaRecepcion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => fechaEntrega)
                </td>
                @switch (item.estado)
                {
                    case "Entregado":
                        <td class="text-success">
                            @Html.DisplayFor(modelItem => item.estado)
                        </td>
                        break;
                    case "Rechazado":
                        <td class="text-danger">
                            @Html.DisplayFor(modelItem => item.estado)
                        </td>
                        break;
                    default:
                        <td class="text-primary">
                            @Html.DisplayFor(modelItem => item.estado)
                        </td>
                        break;
                }

            </tr>
        }

    </table>
</div>

ProyectoEnvios/Views/Envio/registrarEnvio.cshtml
@model ProyectoEnvios.Models.EnvioCS

@{
    ViewBag.Title = "Registro de envios";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Registrar Envio</h2>

@using (Html.BeginForm())
{


    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @if (ViewData["Exito"] != null)
        {
            <div class="alert alert-success" role="alert">
                <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
                <span class="sr-only">Exito:</span>
                @ViewData["Exito"].ToString()
            </div>
        }
        @if (ViewData["Error"] != null)
        {
            <div class="alert alert-danger" role="alert">
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                <span class="sr-only">Error:</span>
                @ViewData["Error"].ToString()
                @Html.ActionLink("Registre al cliente aqui..", "agregarCliente", "Trabajador", null, new { target = "_blank" })
            </div>
        }

        <div class="container-fluid">

            <div class="row">
                <div class="col-md-5 col-md-offset-1">
                    <div class="form-group">
                        @Html.LabelFor(model => model.idRemitente, htmlAttributes: new { @class = "control-label col-md-5" })
                        <br /><br />
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.idRemitente, new { htmlAttributes = new { @class = "form-control", @placeholder = "Documento de identidad" } })
                            @Html.ValidationMessageFor(model => model.idRemitente, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="col-md-5 col-md-offset-1">
                    <div class="form-group">
                        @Html.LabelFor(model => model.idDestinatario, htmlAttributes: new { @class = "control-label col-md-5" })
                        <br /><br />
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.idDestinatario, new { htmlAttributes = new { @class = "form-control", @placeholder = "Documento de identidad" } })
                            @Html.ValidationMessageFor(model => model.idDestinatario, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-5 col-md-offset-1">
                    <div class="form-group">
                        @Html.LabelFor(model => model.origen, htmlAttributes: new { @class = "control-label col-md-5" })
                        <br /><br />
                        <div class="col-md-10">
                            @Html.Action("_ListarCiudades", new { id = 1 })
                            @Html.ValidationMessageFor(model => model.idOrigen, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="col-md-5 col-md-offset-1">
                    <div class="form-group">
                        @Html.LabelFor(model => model.destino, htmlAttributes: new { @class = "control-label col-md-5" })
                        <br /><br />
                        <div class="col-md-10">
                            @Html.Action("_ListarCiudades", new { id = 0 })
                            @Html.ValidationMessageFor(model => model.idDestino, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-5 col-md-offset-1">
                    <div class="form-group">
                        @Html.LabelFor(model => model.tipoProducto, htmlAttributes: new { @class = "control-label col-md-5" })
                        <br /><br />
                        <div class="col-md-10">
                            @Html.Action("_ListarProductos")
                            @Html.ValidationMessageFor(model => model.idTipoProducto, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="col-md-5 col-md-offset-1">
                    <div class="form-group">
                        @Html.LabelFor(model => model.peso, htmlAttributes: new { @class = "control-label col-md-5" })
                        <br /><br />
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.peso, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.peso, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-5 col-md-offset-1">
                    <div class="form-group">
                        @Html.LabelFor(model => model.direccionDestino, htmlAttributes: new { @class = "control-label col-md-5" })
                        <br /><br />
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.direccionDestino, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.direccionDestino, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="col-md-5 col-md-offset-1">
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <br /><br />
                            <input type="submit" value="Registrar" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <hr />

    </div>
}

<div>
    @Html.ActionLink("Volver Atras", "Index")
</div>